from .AIOne import AIOne
from .AITwo import AITwo
from .AIThree import AIThree
from .AIFour import AIFour
from .AIFive import AIFive
from .AISix import AISix
from .AISeven import AISeven
from .AIEight import AIEight
from .AINine import AINine
from .game import Game
